### ISSUE TITLE
Is there any actual code available please?

### ISSUE THREAD

**Issue by conceptrat** [gitzhou/sv-aqi-public#1]
I'm not seeing any actual code available in the repo.  Just a ReadMe with some basic bits of information and a copy and paste of all the hashes????

**Comment by gitzhou** [comment]
Yes. Code is not open sourced yet.

**Comment by conceptrat** [comment]
Ah okay.

Are you planning to do that?

Or will it stay closed?

**Comment by gitzhou** [comment]
Ah, probably, yet for now there is still a lot of work need to do, that priority higher than open source.

**Comment by conceptrat** [comment]
Fair enough.

Although if you made the source available then you might get some help with
issues and enhancements for free 😁 Open Source often leads to other
developers keen to assist. Helps spread the load and might even help the
project get some traction.
